<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('users', function (Blueprint $table) {
            $table->id();
            $table->string('role');
            $table->string('nama');
            $table->string('nip')->nullable();
            $table->string('jabatan')->nullable();
            $table->string('nomor_hp')->nullable();
            $table->string('status')->nullable();
            $table->string('foto')->nullable();
            $table->string('email')->unique()->nullable();
            $table->timestamp('email_verified_at')->nullable();
            $table->string('password');
            $table->rememberToken();
            $table->timestamps();
        });

        DB::table('users')->insert(
            array(
                // THE ADMINs[
                [
                    'role' => 'superadmin',
                    'nama' => 'ADMIN SEKRETARIAT',
                    'nip' => '15243',
                    'jabatan' => null,
                    'nomor_hp' => null,
                    'status' => null,
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'admin',
                    'nama' => 'ADMIN BIDANG ANGGARAN',
                    'nip' => '15243',
                    'jabatan' => null,
                    'nomor_hp' => null,
                    'status' => null,
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'admin',
                    'nama' => 'ADMIN BIDANG AKUNTANSI',
                    'nip' => '15243',
                    'jabatan' => null,
                    'nomor_hp' => null,
                    'status' => null,
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'admin',
                    'nama' => 'ADMIN PERBENDAHARAAN DAN KAS DAERAH',
                    'nip' => '15243',
                    'jabatan' => null,
                    'nomor_hp' => null,
                    'status' => null,
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'admin',
                    'nama' => 'ADMIN ASET DAERAH',
                    'nip' => '15243',
                    'jabatan' => null,
                    'nomor_hp' => null,
                    'status' => null,
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                // THE USERS
                [
                    'role' => 'Kepala Badan',
                    'nama' => 'Drs. H. ASEP GOPARULLAH, M.Pd',
                    'nip' => '19700215 198903 1 004',
                    'jabatan' => 'Kepala Badan',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'Sekretaris Badan',
                    'nama' => 'Hj. HESTI WIDIAWATI, SE, M.M',
                    'nip' => '19770725 200312 2 010',
                    'jabatan' => 'Sekretaris Badan',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'Kepala Bidang',
                    'nama' => 'DEMY RAHAYU, SP',
                    'nip' => '19701215 200801 1 019',
                    'jabatan' => 'Kabid Anggaran',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'Kepala Bidang',
                    'nama' => 'Hj. YENI MULYANI, SE, M.M',
                    'nip' => '19670906 199203 2 008',
                    'jabatan' => 'Kabid Aset Daerah',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'Kepala Bidang',
                    'nama' => 'GHUFRON AFANDI, SE, M.M',
                    'nip' => '19770621 200902 1 002',
                    'jabatan' => 'Kabid Akuntansi',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'Kepala Bidang',
                    'nama' => 'TENI NURHAYATI, SE, M.M',
                    'nip' => '19730603 201101 2 001',
                    'jabatan' => 'Kabid Perbendaharaan dan Kas Daerah',
                    'nomor_hp' => null,
                    'status' => 'tidak aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'Kepala Sub Bidang',
                    'nama' => 'YANI SULAEMAN AGUSTIN, S.Sos, M.Si',
                    'nip' => '19750723 200701 1 003',
                    'jabatan' => 'Kasubid Penatausahaan Aset Daerah',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'Kepala Sub Bidang',
                    'nama' => 'RUDI KURNIAWAN, ST',
                    'nip' => '19800520 200604 1 012',
                    'jabatan' => 'Kasubid Perbendaharaan',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'Kepala Sub Bidang',
                    'nama' => 'DEWI ZAKIYAH, SE, M.Si',
                    'nip' => '19760402 201001 2 003',
                    'jabatan' => 'Kasubid Kas Daerah',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'Kepala Sub Bidang',
                    'nama' => 'ASEP RIO, SH',
                    'nip' => '19760319 200901 1 007',
                    'jabatan' => 'Kasubid pemanfaatan dan Pengamanan Aset Daerah',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'Kepala Sub Bidang',
                    'nama' => 'SURYA AGUSTINUS RIFFENDI, SE',
                    'nip' => '19830818 200902 1 002',
                    'jabatan' => 'Kasubid Perencanaan Anggaran',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                
                [
                    'role' => 'staf',
                    'nama' => 'YANI KAMILA, S.Sos, M.Si',
                    'nip' => '19750325 200604 2 030',
                    'jabatan' => 'Analis Kepegawaian Ahli Muda',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'staf',
                    'nama' => 'NUNIEK YUNIA WIDIATI R, SE, M.M',
                    'nip' => '19790606 200901 2 011',
                    'jabatan' => 'Penelaah Pendapatan dan Belanja',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'staf',
                    'nama' => 'RENI MARIATI, SE, M.M',
                    'nip' => '19751028 200902 2 002',
                    'jabatan' => 'Analis Keuangan Pusat dan Daerah Ahli Muda',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'staf',
                    'nama' => 'JESICA ARIZONA, ST, M.M',
                    'nip' => '19870111 201001 2 010',
                    'jabatan' => 'Perencana Ahli Muda',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'staf',
                    'nama' => 'TITA RAHAYU, SE',
                    'nip' => '19780324 200801 2 005',
                    'jabatan' => 'Analis Perbendaharaan',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'staf',
                    'nama' => 'DODI MUSADAD, SE',
                    'nip' => '19740610 200901 1 005',
                    'jabatan' => 'Analis Pembayaran Perhitungan Pihak Ketiga dan Pembayaran Tuntutan Ganti Rugi',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'staf',
                    'nama' => 'WINI NURYANI, SE, M.M',
                    'nip' => '19780318 201001 2 001',
                    'jabatan' => 'Analis Perbendaharaan',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'staf',
                    'nama' => 'DIANA APRIANTY, SE, M.Si',
                    'nip' => '19810420 201001 2 002',
                    'jabatan' => 'Analis Pelaporan dan Transaksi Keuangan',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'staf',
                    'nama' => 'JIMMI BUDI MULIA, SE, M.M',
                    'nip' => '19811020 200312 1 001',
                    'jabatan' => 'Penata Keuangan',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'staf',
                    'nama' => 'RICKY SEPTIAN, SE',
                    'nip' => '19860922 201101 1 002',
                    'jabatan' => 'Analis Laporan Realisasi Anggaran',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'staf',
                    'nama' => 'IIS KURNIA, S.IP',
                    'nip' => '19821122 200801 2 006',
                    'jabatan' => 'Penyusun Laporan Keuangan',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'staf',
                    'nama' => 'ADE SYAWALUDIN, SE, M.M',
                    'nip' => '19780901 200504 1 001',
                    'jabatan' => 'Penyusun Rencana Kebutuhan Sarana dan Prasarana',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'staf',
                    'nama' => 'NITA INSYANI, S.IP',
                    'nip' => '19821008 200901 2 003',
                    'jabatan' => 'Analis Perencanaan, Evaluasi dan Pelaporan',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'staf',
                    'nama' => 'EKA LISMAYATI, SE',
                    'nip' => '19831115 200902 2 004',
                    'jabatan' => 'Bendahara',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'staf',
                    'nama' => 'VERA PRAMANITA, SE',
                    'nip' => '19840319 201503 2 003',
                    'jabatan' => 'Analis Laporan Realisasi Anggaran',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'staf',
                    'nama' => 'YOVI MULYANA, SE, M.Si',
                    'nip' => '19861207 201503 1 003',
                    'jabatan' => 'Analis Kebijakan Klasifikasi Barang',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'staf',
                    'nama' => 'IIS PITRI ANADEWI, SE, M.M',
                    'nip' => '19860924 201101 2 003',
                    'jabatan' => 'Penata Keuangan',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'staf',
                    'nama' => 'ASRI DAMAYANTI, S.IP',
                    'nip' => '19790510 200701 2 011',
                    'jabatan' => 'Penata Keuangan',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'staf',
                    'nama' => 'DERRY TAUPIQ, A.Md',
                    'nip' => '19821005 200902 1 003',
                    'jabatan' => 'Analis Aset Daerah',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'staf',
                    'nama' => 'AGUS KURNIAWAN, S.IP',
                    'nip' => '19710902 200312 1 006',
                    'jabatan' => 'Penyusun Rencana Kebutuhan Rumah Tangga dan Perlengkapan',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'staf',
                    'nama' => 'REDI CAHYADI, ST, M.M',
                    'nip' => '19860729 201101 1 002',
                    'jabatan' => 'Penata Keuangan',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'staf',
                    'nama' => 'SHINTA FARIDZATUNISA, S. Sos',
                    'nip' => '19810820 200901 2 006',
                    'jabatan' => 'Analis Keuangan',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'staf',
                    'nama' => 'INDA RIZQI FARHANI, A.Md',
                    'nip' => '19890628 201101 2 003',
                    'jabatan' => 'Bendahara',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'staf',
                    'nama' => 'IRMA SURYANI, S.IP',
                    'nip' => '19791110 200901 2 008',
                    'jabatan' => 'Analis Pengembangan SDM Aparatur',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'staf',
                    'nama' => 'FEBI SATRIANA, SE, M.Si',
                    'nip' => '19860215 201001 1 002',
                    'jabatan' => 'Verifikator',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'staf',
                    'nama' => 'KIKI WAHYUNI, S.IP',
                    'nip' => '19840612 200901 2 009',
                    'jabatan' => 'Analis Standar Harga',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'staf',
                    'nama' => 'SUPENO, S.IP',
                    'nip' => '19770916 201001 1 002',
                    'jabatan' => 'Analis Aset Daerah',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'staf',
                    'nama' => 'RENI RENITA, S.IP',
                    'nip' => '19781129 201001 2 001',
                    'jabatan' => 'Penata Laporan Keuangan',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'staf',
                    'nama' => 'NANO SUSANTO, S.IP',
                    'nip' => '19840801 201001 1 003',
                    'jabatan' => 'Analis Laporan Realisasi Anggaran',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'staf',
                    'nama' => 'DIAN MAYASARI, S.IP',
                    'nip' => '19851005 201001 2 001',
                    'jabatan' => 'Analis Perencanaan, Evaluasi dan Pelaporan',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'staf',
                    'nama' => 'ASEP RIDWAN, SE',
                    'nip' => '19851206 201001 1 001',
                    'jabatan' => 'Analis Kebijakan Klasifikasi Barang',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'staf',
                    'nama' => 'GUGIALANA WAHYU',
                    'nip' => '19820702 200501 1 005',
                    'jabatan' => 'Analis Laporan Realisasi Anggaran',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'staf',
                    'nama' => 'INEU NURAENI',
                    'nip' => '19731115 200701 2 008',
                    'jabatan' => 'Analis Penyelesaian Laporan Hasil Pemeriksaan',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'staf',
                    'nama' => 'DIDIN BAYANUDDIN',
                    'nip' => '19730902 200701 1 005',
                    'jabatan' => 'Analis Laporan Realisasi Anggaran',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'staf',
                    'nama' => 'FILZA RIDWAN ROSHAN, S.Tr.IP',
                    'nip' => '19971101 202208 1 001',
                    'jabatan' => 'Sekretaris',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'staf',
                    'nama' => 'ANGGA PRAMADITA, A.Md',
                    'nip' => '19820308 201503 1 001',
                    'jabatan' => 'Arsiparis Terampil',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'staf',
                    'nama' => 'DIAN NUGRAHA, A.Md',
                    'nip' => '19840602 201503 1 001',
                    'jabatan' => 'Arsiparis Terampil',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'staf',
                    'nama' => 'RIZKI HIKMAWAN, A.Md',
                    'nip' => '19920226 201903 1 004',
                    'jabatan' => 'Pranata Komputer Pelaksana',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'staf',
                    'nama' => 'YUDI DWI PERMADI',
                    'nip' => '19740314 201212 1 001',
                    'jabatan' => 'Pengolah Data Kebijakan Klasifikasi Barang',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'staf',
                    'nama' => 'WAHYU YOGA PAMUNGKAS, A.Md, Ak',
                    'nip' => '20000516 202408 1 001',
                    'jabatan' => 'Pengolah Data dan Informasi',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'staf',
                    'nama' => 'EGITA ANNISSAA ARDIANA, A.Md, AK',
                    'nip' => '20011218 202408 2 001',
                    'jabatan' => 'Pengolah Data dan Informasi',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'staf',
                    'nama' => 'ADI ABDUL GANI, S.Kom',
                    'nip' => '19911126 202321 1 017',
                    'jabatan' => 'Pranata Komputer',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                
            )
            );

        Schema::create('password_reset_tokens', function (Blueprint $table) {
            $table->string('email')->primary();
            $table->string('token');
            $table->timestamp('created_at')->nullable();
        });

        Schema::create('sessions', function (Blueprint $table) {
            $table->string('id')->primary();
            $table->foreignId('user_id')->nullable()->index();
            $table->string('ip_address', 45)->nullable();
            $table->text('user_agent')->nullable();
            $table->longText('payload');
            $table->integer('last_activity')->index();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('users');
        Schema::dropIfExists('password_reset_tokens');
        Schema::dropIfExists('sessions');
    }
};
