<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('users', function (Blueprint $table) {
            $table->id();
            $table->string('role');
            $table->string('nama');
            $table->string('nip')->nullable();
            $table->string('jabatan')->nullable();
            $table->string('nomor_hp')->nullable();
            $table->string('status')->nullable();
            $table->string('foto')->nullable();
            $table->string('email')->unique()->nullable();
            $table->timestamp('email_verified_at')->nullable();
            $table->string('password');
            $table->rememberToken();
            $table->timestamps();
        });

        DB::table('users')->insert(
            array(
                // THE ADMINs[
                [
                    'role' => 'Superadmin',
                    'nama' => 'ADMIN SEKRETARIAT',
                    'nip' => '123451',
                    'jabatan' => null,
                    'nomor_hp' => null,
                    'status' => null,
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'Admin',
                    'nama' => 'ADMIN BIDANG ANGGARAN',
                    'nip' => '123452',
                    'jabatan' => null,
                    'nomor_hp' => null,
                    'status' => null,
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'Admin',
                    'nama' => 'ADMIN BIDANG AKUNTANSI',
                    'nip' => '123453',
                    'jabatan' => null,
                    'nomor_hp' => null,
                    'status' => null,
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'Admin',
                    'nama' => 'ADMIN PERBENDAHARAAN DAN KAS DAERAH',
                    'nip' => '123454',
                    'jabatan' => null,
                    'nomor_hp' => null,
                    'status' => null,
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'Admin',
                    'nama' => 'ADMIN ASET DAERAH',
                    'nip' => '123455',
                    'jabatan' => null,
                    'nomor_hp' => null,
                    'status' => null,
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                // THE USERS
                [
                    'role' => 'Kepala Badan',
                    'nama' => 'Drs. H. ASEP GOPARULLAH, M.Pd',
                    'nip' => '197002151989031004',
                    'jabatan' => 'Kepala Badan',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'Sekretaris Badan',
                    'nama' => 'Hj. HESTI WIDIAWATI, SE, M.M',
                    'nip' => '197707252003122010',
                    'jabatan' => 'Sekretaris Badan',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'Kepala Bidang',
                    'nama' => 'DEMY RAHAYU, SP',
                    'nip' => '197012152008011019',
                    'jabatan' => 'Kabid Anggaran',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'Kepala Bidang',
                    'nama' => 'Hj. YENI MULYANI, SE, M.M',
                    'nip' => '196709061992032008',
                    'jabatan' => 'Kabid Aset Daerah',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'Kepala Bidang',
                    'nama' => 'GHUFRON AFANDI, SE, M.M',
                    'nip' => '197706212009021002',
                    'jabatan' => 'Kabid Akuntansi',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'Kepala Bidang',
                    'nama' => 'TENI NURHAYATI, SE, M.M',
                    'nip' => '197306032011012001',
                    'jabatan' => 'Kabid Perbendaharaan dan Kas Daerah',
                    'nomor_hp' => null,
                    'status' => 'tidak aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'Kepala Sub Bidang',
                    'nama' => 'YANI SULAEMAN AGUSTIN, S.Sos, M.Si',
                    'nip' => '197507232007011003',
                    'jabatan' => 'Kasubid Penatausahaan Aset Daerah',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'Kepala Sub Bidang',
                    'nama' => 'RUDI KURNIAWAN, ST',
                    'nip' => '198005202006041012',
                    'jabatan' => 'Kasubid Perbendaharaan',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'Kepala Sub Bidang',
                    'nama' => 'DEWI ZAKIYAH, SE, M.Si',
                    'nip' => '197604022010012003',
                    'jabatan' => 'Kasubid Kas Daerah',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'Kepala Sub Bidang',
                    'nama' => 'ASEP RIO, SH',
                    'nip' => '197603192009011007',
                    'jabatan' => 'Kasubid pemanfaatan dan Pengamanan Aset Daerah',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'Kepala Sub Bidang',
                    'nama' => 'SURYA AGUSTINUS RIFFENDI, SE',
                    'nip' => '198308182009021002',
                    'jabatan' => 'Kasubid Perencanaan Anggaran',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                
                [
                    'role' => 'Staf',
                    'nama' => 'YANI KAMILA, S.Sos, M.Si',
                    'nip' => '197503252006042030',
                    'jabatan' => 'Analis Kepegawaian Ahli Muda',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'Staf',
                    'nama' => 'NUNIEK YUNIA WIDIATI R, SE, M.M',
                    'nip' => '197906062009012011',
                    'jabatan' => 'Penelaah Pendapatan dan Belanja',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'Staf',
                    'nama' => 'RENI MARIATI, SE, M.M',
                    'nip' => '197510282009022002',
                    'jabatan' => 'Analis Keuangan Pusat dan Daerah Ahli Muda',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'Staf',
                    'nama' => 'JESICA ARIZONA, ST, M.M',
                    'nip' => '198701112010012010',
                    'jabatan' => 'Perencana Ahli Muda',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'Staf',
                    'nama' => 'TITA RAHAYU, SE',
                    'nip' => '197803242008012005',
                    'jabatan' => 'Analis Perbendaharaan',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'Staf',
                    'nama' => 'DODI MUSADAD, SE',
                    'nip' => '197406102009011005',
                    'jabatan' => 'Analis Pembayaran Perhitungan Pihak Ketiga dan Pembayaran Tuntutan Ganti Rugi',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'Staf',
                    'nama' => 'WINI NURYANI, SE, M.M',
                    'nip' => '197803182010012001',
                    'jabatan' => 'Analis Perbendaharaan',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'Staf',
                    'nama' => 'DIANA APRIANTY, SE, M.Si',
                    'nip' => '198104202010012002',
                    'jabatan' => 'Analis Pelaporan dan Transaksi Keuangan',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'Staf',
                    'nama' => 'JIMMI BUDI MULIA, SE, M.M',
                    'nip' => '198110202003121001',
                    'jabatan' => 'Penata Keuangan',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'Staf',
                    'nama' => 'RICKY SEPTIAN, SE',
                    'nip' => '198609222011011002',
                    'jabatan' => 'Analis Laporan Realisasi Anggaran',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'Staf',
                    'nama' => 'IIS KURNIA, S.IP',
                    'nip' => '198211222008012006',
                    'jabatan' => 'Penyusun Laporan Keuangan',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'Staf',
                    'nama' => 'ADE SYAWALUDIN, SE, M.M',
                    'nip' => '197809012005041001',
                    'jabatan' => 'Penyusun Rencana Kebutuhan Sarana dan Prasarana',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'Staf',
                    'nama' => 'NITA INSYANI, S.IP',
                    'nip' => '198210082009012003',
                    'jabatan' => 'Analis Perencanaan, Evaluasi dan Pelaporan',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'Staf',
                    'nama' => 'EKA LISMAYATI, SE',
                    'nip' => '198311152009022004',
                    'jabatan' => 'Bendahara',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'Staf',
                    'nama' => 'VERA PRAMANITA, SE',
                    'nip' => '198403192015032003',
                    'jabatan' => 'Analis Laporan Realisasi Anggaran',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'Staf',
                    'nama' => 'YOVI MULYANA, SE, M.Si',
                    'nip' => '198612072015031003',
                    'jabatan' => 'Analis Kebijakan Klasifikasi Barang',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'Staf',
                    'nama' => 'IIS PITRI ANADEWI, SE, M.M',
                    'nip' => '198609242011012003',
                    'jabatan' => 'Penata Keuangan',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'Staf',
                    'nama' => 'ASRI DAMAYANTI, S.IP',
                    'nip' => '197905102007012011',
                    'jabatan' => 'Penata Keuangan',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'Staf',
                    'nama' => 'DERRY TAUPIQ, A.Md',
                    'nip' => '198210052009021003',
                    'jabatan' => 'Analis Aset Daerah',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'Staf',
                    'nama' => 'AGUS KURNIAWAN, S.IP',
                    'nip' => '197109022003121006',
                    'jabatan' => 'Penyusun Rencana Kebutuhan Rumah Tangga dan Perlengkapan',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'Staf',
                    'nama' => 'REDI CAHYADI, ST, M.M',
                    'nip' => '198607292011011002',
                    'jabatan' => 'Penata Keuangan',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'Staf',
                    'nama' => 'SHINTA FARIDZATUNISA, S. Sos',
                    'nip' => '198108202009012006',
                    'jabatan' => 'Analis Keuangan',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'Staf',
                    'nama' => 'INDA RIZQI FARHANI, A.Md',
                    'nip' => '198906282011012003',
                    'jabatan' => 'Bendahara',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'Staf',
                    'nama' => 'IRMA SURYANI, S.IP',
                    'nip' => '197911102009012008',
                    'jabatan' => 'Analis Pengembangan SDM Aparatur',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'Staf',
                    'nama' => 'FEBI SATRIANA, SE, M.Si',
                    'nip' => '198602152010011002',
                    'jabatan' => 'Verifikator',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'Staf',
                    'nama' => 'KIKI WAHYUNI, S.IP',
                    'nip' => '198406122009012009',
                    'jabatan' => 'Analis Standar Harga',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'Staf',
                    'nama' => 'SUPENO, S.IP',
                    'nip' => '197709162010011002',
                    'jabatan' => 'Analis Aset Daerah',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'Staf',
                    'nama' => 'RENI RENITA, S.IP',
                    'nip' => '197811292010012001',
                    'jabatan' => 'Penata Laporan Keuangan',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'Staf',
                    'nama' => 'NANO SUSANTO, S.IP',
                    'nip' => '198408012010011003',
                    'jabatan' => 'Analis Laporan Realisasi Anggaran',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'Staf',
                    'nama' => 'DIAN MAYASARI, S.IP',
                    'nip' => '198510052010012001',
                    'jabatan' => 'Analis Perencanaan, Evaluasi dan Pelaporan',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'Staf',
                    'nama' => 'ASEP RIDWAN, SE',
                    'nip' => '198512062010011001',
                    'jabatan' => 'Analis Kebijakan Klasifikasi Barang',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'Staf',
                    'nama' => 'GUGIALANA WAHYU',
                    'nip' => '198207022005011005',
                    'jabatan' => 'Analis Laporan Realisasi Anggaran',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'Staf',
                    'nama' => 'INEU NURAENI',
                    'nip' => '197311152007012008',
                    'jabatan' => 'Analis Penyelesaian Laporan Hasil Pemeriksaan',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'Staf',
                    'nama' => 'DIDIN BAYANUDDIN',
                    'nip' => '197309022007011005',
                    'jabatan' => 'Analis Laporan Realisasi Anggaran',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'Staf',
                    'nama' => 'FILZA RIDWAN ROSHAN, S.Tr.IP',
                    'nip' => '199711012022081001',
                    'jabatan' => 'Sekretaris',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'Staf',
                    'nama' => 'ANGGA PRAMADITA, A.Md',
                    'nip' => '198203082015031001',
                    'jabatan' => 'Arsiparis Terampil',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'Staf',
                    'nama' => 'DIAN NUGRAHA, A.Md',
                    'nip' => '198406022015031001',
                    'jabatan' => 'Arsiparis Terampil',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'Staf',
                    'nama' => 'RIZKI HIKMAWAN, A.Md',
                    'nip' => '199202262019031004',
                    'jabatan' => 'Pranata Komputer Pelaksana',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'Staf',
                    'nama' => 'YUDI DWI PERMADI',
                    'nip' => '197403142012121001',
                    'jabatan' => 'Pengolah Data Kebijakan Klasifikasi Barang',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'Staf',
                    'nama' => 'WAHYU YOGA PAMUNGKAS, A.Md, Ak',
                    'nip' => '200005162024081001',
                    'jabatan' => 'Pengolah Data dan Informasi',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'Staf',
                    'nama' => 'EGITA ANNISSAA ARDIANA, A.Md, AK',
                    'nip' => '200112182024082001',
                    'jabatan' => 'Pengolah Data dan Informasi',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                [
                    'role' => 'Staf',
                    'nama' => 'ADI ABDUL GANI, S.Kom',
                    'nip' => '199111262023211017',
                    'jabatan' => 'Pranata Komputer',
                    'nomor_hp' => null,
                    'status' => 'aktif',
                    'email' => null,
                    'password' => bcrypt('12345'),
                    'foto' => null,
                ],
                
            )
            );

        Schema::create('password_reset_tokens', function (Blueprint $table) {
            $table->string('email')->primary();
            $table->string('token');
            $table->timestamp('created_at')->nullable();
        });

        Schema::create('sessions', function (Blueprint $table) {
            $table->string('id')->primary();
            $table->foreignId('user_id')->nullable()->index();
            $table->string('ip_address', 45)->nullable();
            $table->text('user_agent')->nullable();
            $table->longText('payload');
            $table->integer('last_activity')->index();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('users');
        Schema::dropIfExists('password_reset_tokens');
        Schema::dropIfExists('sessions');
    }
};
